web/management/urls.py
from django.urls import path
from . import views

app_name = 'appointment'

urlpatterns = [
    path('', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('create_temporary_manager/', views.create_temporary_manager, name='create_temporary_manager'),
    path('create_manager/<str:token>/', views.create_manager, name='create_manager'),
    path('done_create_manager/', views.done_create_manager, name='done_create_manager'),
    path('appointment_list/', views.appointment_list, name='appointment_list'),
    path('manager_list/', views.manager_list, name='manager_list'),
    path('edit_manager/<int:manager_id>', views.edit_manager, name='edit_manager'),
    path('delete_manager/<int:manager_id>', views.delete_manager, name='delete_manager'),
]

web/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('appointment/', include('appointment.urls', namespace='appointment')),
    path('management/', include('management.urls', namespace='management')),
]

web/management/models.py
from django.db import models
from django.utils import timezone

from core.models import BaseModel


class TemporaryManager(BaseModel):
    name = models.CharField('名前', max_length=30)
    mail_address = models.EmailField('メールアドレス', max_length=255)
    token = models.CharField('トークン', max_length=128)
    token_expired_at = models.DateTimeField('トークン有効期限')

    class Meta:
        db_table = "temporary_manager"
        verbose_name_plural = "本登録前管理者"

    def __str__(self):
        return '{}（有効期限：{}）'.format(
            self.name, timezone.localtime(self.token_expired_at).strftime("%Y/%m/%d %H:%M:%S"))


class Manager(BaseModel):
    name = models.CharField('名前', max_length=30)
    password = models.CharField('パスワード', max_length=255)
    mail_address = models.EmailField('メールアドレス', max_length=255, unique=True)
    is_authorized = models.BooleanField('承認済みフラグ', default=False)
    is_system_manager = models.BooleanField('システム管理者フラグ', default=False)

    class Meta:
        db_table = "manager"
        verbose_name_plural = "管理者"
        unique_together = ["name", "password"]

    def __str__(self):
        return self.name

web/management/forms.py
from datetime import datetime

from django import forms
from django.core.exceptions import MultipleObjectsReturned, ObjectDoesNotExist, ValidationError

from management.models import Manager, TemporaryManager
from management.utils import make_sha512


class LoginForm(forms.Form):
    name = forms.CharField(label="名前", max_length="30")
    password = forms.CharField(label="パスワード", max_length="255", widget=forms.PasswordInput())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control mt-1'

    def clean(self):
        cleaned_data = self.cleaned_data
        name = cleaned_data.get('name')
        password = cleaned_data.get('password')
        try:
            manager = Manager.objects.get(name=name, password=make_sha512(password))
            if not manager.is_authorized:
                self.add_error(None, "まだ承認されていません。")
        except ObjectDoesNotExist:
            self.add_error('password', "ユーザーネームまたはパスワードが間違っています。")
        except MultipleObjectsReturned:
            self.add_error('password', "同一アカウントが複数存在します。\n管理者にご連絡ください。")

        return cleaned_data


class TemporaryManagerForm(forms.Form):
    name = forms.CharField(label="名前", max_length="30")
    mail_address = forms.EmailField(label="メールアドレス", max_length="255")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control mt-1'

    def clean_mail_address(self):
        now = datetime.now()
        mail_address = self.cleaned_data['mail_address']
        if Manager.objects.filter(mail_address=mail_address).exists():
            self.add_error('mail_address', "このメールアドレスは登録されています。")
        elif TemporaryManager.objects.filter(mail_address=mail_address, token_expired_at__gte=now).exists():
            self.add_error('mail_address', "送信済みの本登録案内メールが有効期限内です。\nメールボックスをご確認ください。")

        return mail_address


class ManagerForm(forms.Form):
    password = forms.CharField(label="パスワード", max_length="255", widget=forms.PasswordInput())
    conf_password = forms.CharField(label="パスワード（確認）", max_length="255", widget=forms.PasswordInput())

    def __init__(self, temp_manager_name, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.temp_manager_name = temp_manager_name
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control mt-1'

    def clean(self):
        cleaned_data = self.cleaned_data
        password = cleaned_data.get('password')
        conf_password = cleaned_data.get('conf_password')
        if not password == conf_password:
            self.add_error('conf_password', "パスワードが一致しません。")
        elif Manager.objects.filter(name=self.temp_manager_name, password=make_sha512(password)).exists():
            self.add_error('conf_password', "このパスワードはご使用できません。")

        return cleaned_data


class AppointmentSearchForm(forms.Form):
    only_my_customer_flg = forms.BooleanField(
        label="自分の担当顧客だけを表示",
        label_suffix='',
        required=False,
        widget=forms.CheckboxInput(
            attrs={
                'class': 'form-check-input me-2',
                'type': 'checkbox',
            }),
    )
    from_visit_date = forms.DateField(
        label="いつから",
        required=False,
        input_formats=['%Y/%m/%d'],
        widget=forms.TextInput(
            attrs={
                'class': 'form-control datetimepicker-input from-date-picker',
                'data-target': '#from-date-picker',
                'placeholder': 'YYYY/mm/dd',
                'autocomplete': 'off',
            }
        )
    )
    to_visit_date = forms.DateField(
        label="いつまで",
        required=False,
        input_formats=['%Y/%m/%d'],
        widget=forms.TextInput(
            attrs={
                'class': 'form-control datetimepicker-input to-date-picker',
                'data-target': '#to-date-picker',
                'placeholder': 'YYYY/mm/dd',
                'autocomplete': 'off',
            }
        )
    )

    def clean(self):
        cleaned_data = self.cleaned_data
        print("cleaned_data", cleaned_data)
        from_visit_date = cleaned_data["from_visit_date"]
        to_visit_date = cleaned_data["to_visit_date"]
        if from_visit_date and to_visit_date and to_visit_date < from_visit_date:
            self.add_error('to_visit_date', "「いつまで」の日付は「いつから」より後日にしてください。")

        return cleaned_data


class ManagerSearchForm(forms.Form):
    only_not_authorized_flg = forms.BooleanField(
        label='未承認の管理者のみ表示',
        label_suffix='',
        required=False,
        widget=forms.CheckboxInput(
            attrs={
                'class': 'form-check-input me-2',
                'type': 'checkbox',
            }),
    )


class EditManagerForm(forms.Form):
    name = forms.CharField(
        label='名前',
        max_length="30",
        widget=forms.TextInput(
            attrs={
                'class': 'form-control mt-1',
            }
        )
    )
    mail_address = forms.EmailField(
        label="メールアドレス",
        max_length="255",
        widget=forms.TextInput(
            attrs={
                'class': 'form-control mt-1',
            }
        )
    )
    is_authorized = forms.BooleanField(
        label="管理者承認",
        required=False,
        widget=forms.CheckboxInput(
            attrs={
                'class': 'btn-check',
                'type': 'checkbox',
            }),
    )
    is_system_manager = forms.BooleanField(
        label="システムマネージャー",
        required=False,
        widget=forms.CheckboxInput(
            attrs={
                'class': 'btn-check',
                'type': 'checkbox',
            }),
    )
    hidden_is_system_manager = forms.BooleanField(
        required=False,
        widget=forms.HiddenInput,
    )

    def __init__(self, login_manager_id: int, manager_id: int, initial_dict: dict, *args, **kwargs):
        super().__init__(*args, **kwargs)
        manager = Manager.objects.get(id=manager_id)
        self.before_is_system_manager = manager.is_system_manager
        self.login_manager_id = login_manager_id
        self.manager_id = manager_id
        for k, v in initial_dict.items():
            self.fields[k].initial = v
        if login_manager_id == manager_id:
            self.fields['is_system_manager'].widget.attrs['disabled'] = 'disabled'
            self.fields['hidden_is_system_manager'].initial = self.fields['is_system_manager'].initial
        else:
            del self.fields['hidden_is_system_manager']

web/management/views.py
import hashlib
from datetime import datetime

from dateutil.relativedelta import relativedelta

from django.contrib import messages
from django.core.exceptions import MultipleObjectsReturned, ObjectDoesNotExist
from django.http.response import HttpResponse
from django.http.request import HttpRequest
from django.shortcuts import redirect, render
from django.views.decorators.http import require_GET, require_POST

from appointment.models import Appointment
from core.decorators import basic_auth, require_GET_POST, manager_login_required
from management.forms import (
    AppointmentSearchForm,
    EditManagerForm,
    LoginForm,
    TemporaryManagerForm,
    ManagerForm,
    ManagerSearchForm,
)
from management.models import Manager, TemporaryManager
from management.utils import make_page_obj, make_sha512, send_mail_temp_user_registration_done


@require_GET_POST
def login(request: HttpRequest):
    """ログイン"""
    if request.session.get('manager_id'):
        return redirect('management:appointment_list')
    form = LoginForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            manager = Manager.objects.get(name=form.cleaned_data['name'])
            request.session["manager_id"] = manager.id
            return redirect('management:appointment_list')

    return render(request, 'management/no_menu/login.html', {'form': form})


@manager_login_required
@require_POST
def logout(request: HttpRequest):
    """ログアウト"""
    if request.session.get('manager_id'):
        del request.session["manager_id"]
    return redirect('management:login')


@require_GET_POST
def create_temporary_manager(request: HttpRequest):
    """管理者仮登録"""
    form = TemporaryManagerForm(request.POST or None)
    if request.method == "POST":
        form.is_valid()
        if form.is_valid():
            cleaned_data = form.cleaned_data
            name = cleaned_data['name']
            mail_address = cleaned_data['mail_address']
            # トークン作成
            now = datetime.now()
            token_str = name + mail_address + str(now)
            token = make_sha512(token_str)
            token_expired_at = now + relativedelta(minutes=30)
            # 仮登録ユーザー作成
            # メールアドレスが有効か確認
            is_success = send_mail_temp_user_registration_done(request, token, token_expired_at, mail_address)
            if is_success:
                # DBに仮管理者ユーザーを登録
                TemporaryManager.objects.create(
                    name=name,
                    mail_address=mail_address,
                    token=token,
                    token_expired_at=token_expired_at,
                )
                messages.success(request, '本登録案内メールを送信しました。')
                messages.success(request, 'メールフォルダをご確認ください。')
                return redirect('management:create_temporary_manager')
            else:
                messages.error(request, 'メール送信に失敗しました。\nメールアドレスが正しいかご確認ください。')
                return redirect('management:create_temporary_manager')

    return render(request, 'management/no_menu/create_temporary_manager.html', {'form': form})


@require_GET_POST
def create_manager(request: HttpRequest, token: str):
    """管理者本登録"""
    now = datetime.now()
    try:
        temp_manager = TemporaryManager.objects.get(token=token, token_expired_at__gte=now)
    except (MultipleObjectsReturned, ObjectDoesNotExist):
        return HttpResponse("無効なトークンです。")

    form = ManagerForm(temp_manager.name, request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            cleaned_data = form.cleaned_data
            password = cleaned_data.get('password')
            Manager.objects.create(
                name=temp_manager.name,
                password=hashlib.sha512(password.encode('utf-8')).hexdigest(),
                mail_address=temp_manager.mail_address,
                )
            temp_manager.delete()
            return redirect('management:done_create_manager')

    return render(request, 'management/no_menu/create_manager.html', {'form': form})


@require_GET
def done_create_manager(request: HttpRequest):
    return render(request, 'management/no_menu/done_create_manager.html')


@require_GET_POST
@manager_login_required
def appointment_list(request: HttpRequest):
    now = datetime.now()
    appointment_qs = None
    form = AppointmentSearchForm(request.GET or None)
    if form:
        if form.is_valid():
            cleaned_data = form.cleaned_data
            only_my_customer_flg = cleaned_data["only_my_customer_flg"]
            from_visit_date = cleaned_data["from_visit_date"]
            to_visit_date = cleaned_data["to_visit_date"]

            appointment_qs = Appointment.objects.all()
            if only_my_customer_flg:
                pass
                # appointment_qs.filter(manager=request.manager)
            if from_visit_date:
                appointment_qs.filter(visit_at__gte=from_visit_date)
            if to_visit_date:
                appointment_qs.filter(manager=to_visit_date)
    if not appointment_qs:
        appointment_qs = Appointment.objects.filter(visit_at__range=(now, now+relativedelta(months=1)))

    page_range = 20
    page_obj = make_page_obj(appointment_qs, page_range, request.GET.get('page'))

    ret = {"form": form, "page_obj": page_obj}

    return render(request, 'management/menu/appointment_list.html', ret)


@require_GET
@manager_login_required
@basic_auth
def manager_list(request: HttpRequest):
    manager_qs = Manager.objects.all().order_by('name')
    form = ManagerSearchForm(request.GET or None)
    if form.is_valid():
        only_not_authorized_flg = form.cleaned_data["only_not_authorized_flg"]
        if only_not_authorized_flg:
            manager_qs = manager_qs.filter(is_authorized=False)
    print(manager_qs)
    page_range = 20
    page_obj = make_page_obj(manager_qs, page_range, request.GET.get('page'))
    print(page_obj)

    ret = {"form": form, "page_obj": page_obj}

    return render(request, 'management/menu/manager_list.html', ret)


@require_GET_POST
@manager_login_required
@basic_auth
def edit_manager(request: HttpRequest, manager_id: int):
    try:
        manager = Manager.objects.get(id=manager_id)
    except (ObjectDoesNotExist, MultipleObjectsReturned):
        messages.error(request, "該当するマネージャーが存在しません。")
        return redirect('management:manager_list')
    initial_dict = {
        "name": manager.name,
        "mail_address": manager.mail_address,
        "is_authorized": manager.is_authorized,
        "is_system_manager": manager.is_system_manager,
    }
    form = EditManagerForm(
        request.manager.id,
        manager_id,
        initial_dict,
        request.POST or None,
    )
    if request.method == "POST":
        if form.is_valid():
            cleaned_data = form.cleaned_data
            manager.name = cleaned_data["name"]
            manager.mail_address = cleaned_data["mail_address"]
            manager.is_authorized = cleaned_data["is_authorized"]
            if request.manager == manager:
                manager.is_system_manager = cleaned_data["hidden_is_system_manager"]
            else:
                manager.is_system_manager = cleaned_data["is_system_manager"]
            manager.save()
            messages.success(request, "プロフィールが更新されました。")
            return redirect('management:edit_manager', manager.id)
    return render(request, 'management/menu/edit_manager.html', {'form': form, 'manager': manager})


@require_POST
@manager_login_required
def delete_manager(request: HttpRequest, manager_id: int):
    manager = Manager.objects.get(id=manager_id)
    delete_count = manager.delete()
    if delete_count > 0:
        messages.success(request, "id: {} {}さんのユーザー削除に成功しました。".format(manager.id, manager.name))
    else:
        messages.error(request, "id: {} {}さんのユーザー削除が失敗しました。".format(manager.id, manager.name))
    return redirect('management:manager_list')

web/templates/management/menu/appointment_list.html
{% extends 'management/menu/base.html' %}
{% load static %}

{% block title %}予約一覧{% endblock %}

{% block style %}
<link href="{% static 'css/datetimepicker.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="container">
  <!-- search_form row -->
  <div class="row mt-5 justify-content-center">
    <div class="col-12">
      <div class="card">
        <div class="card-body pt-2 pb-0">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              <a data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false"
                 aria-controls="collapseExample" style="display: block;">
                <i class="fas fa-search me-2"></i>検索条件
              </a>
            </li>
            <li class="list-group-item">
              <div class="collapse mb-2" id="collapseExample">
                <form method="get">
                  {% include 'include/errors.html' with errors=form.non_field_errors %}
                  
                  <!-- from_visit_date -->
                  <div class="mb-3">
                    <span>{{ form.from_visit_date.label_tag }}</span>
                    <div class="input-group date mb-3" id="from-date-picker" data-target-input="nearest">
                      {{ form.from_visit_date }}
                      <div class="input-group-text from-date-picker-icon" data-target="#from-date-picker"
                           data-toggle="datetimepicker">
                        <i class="far fa-calendar-alt"></i>
                      </div>
                    </div>
                    {% include 'include/errors.html' with errors=form.from_visit_date.errors %}
                  </div>
                  <!-- end of from_visit_date -->
                  <!-- to_visit_date -->
                  <div class="mb-3">
                    <span>{{ form.to_visit_date.label_tag }}</span>
                    <div class="input-group date mb-3" id="to-date-picker" data-target-input="nearest">
                      {{ form.to_visit_date }}
                      <div class="input-group-text to-date-picker-icon" data-target="#to-date-picker"
                           data-toggle="datetimepicker">
                        <i class="far fa-calendar-alt"></i>
                      </div>
                    </div>
                    {% include 'include/errors.html' with errors=form.to_visit_date.errors %}
                  </div>
                  <!-- end of from_visit_date -->
                  <div class="mb-3">
                    {{ form.only_my_customer_flg }}{{ form.only_my_customer_flg.label_tag }}
                    {% include 'include/errors.html' with errors=form.only_my_customer_flg.errors %}
                  </div>
                  
                  <div class="d-grid gap-2">
                    <button type="submit" class="btn btn-primary">検索</button>
                  </div>
                
                </form>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <!-- end of search_form row -->
  
  <!-- page_obj row -->
  <div class="row">
    <div class="col-12">
      {% for o in page_obj %}
      {% endfor %}
    </div>
  </div>
  
  <!-- end of page_obj row -->

</div>
{% endblock content %}

{% block script %}
<script src="{% static 'js/appointment_list.js' %}" type="text/javascript"></script>
{% endblock %}

web/templates/management/menu/base.html
{% extends 'base.html' %}
{% load static %}

{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid justify-content-start">
    <a class="navbar-brand" href="{% url 'management:login' %}">メニュー</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'management:appointment_list' %}">予約リスト</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'management:manager_list' %}">管理者リスト</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Link
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Link</a>
        </li>
      </ul>
      <form class="d-flex" action="{% url 'management:logout' %}" method="post">
        {% csrf_token %}
        <button class="btn btn-outline-danger" type="submit">ログアウト</button>
      </form>
    </div>
  </div>
</nav>
{% endblock %}

web/templates/management/menu/edit_manager.html
{% extends 'management/menu/base.html' %}
{% load static %}

{% block title %}予約一覧{% endblock %}

{% block style %}
<link href="{% static 'css/datetimepicker.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="container">
  {% include 'include/messages.html' %}
  <!-- search_form row -->
  <div class="row mt-3 justify-content-center">
    <div class="col-12">
      <form id="edit_manager_form" method="post" action="">
        {% csrf_token %}
        <ul class="list-group">
          <li class="list-group-item">
            <div class="mt-2 mb-3">
              {{ form.name.label_tag }}{{ form.name }}
              {% include 'include/errors.html' with errors=form.name.errors %}
            </div>
            
            <div class="mb-3">
              {{ form.mail_address.label_tag }}{{ form.mail_address }}
              {% include 'include/errors.html' with errors=form.mail_address.errors %}
            </div>
            
            <div class="mb-3">
              {{ form.is_authorized.label_tag }}<br>
              <div class="mt-1 d-grid gap-2">
                {{ form.is_authorized }}
                <label id="btn_label_is_authorized" class="btn btn-outline-success" for="id_is_authorized">
                  {% if manager.is_authorized %}<i class="fas fa-user-check"></i>{% else %}<i class="fas fa-user-slash"></i>{% endif %}
                </label>
              </div>
              {% include 'include/errors.html' with errors=form.is_authorized.errors %}
            </div>
            
            <div class="mb-3">
              {{ form.is_system_manager.label_tag }}<br>
              <div class="mt-1 d-grid gap-2">
                {{ form.is_system_manager }}
                <label id="btn_label_is_system_manager" class="btn btn-outline-success" for="id_is_system_manager">
                  {% if manager.is_system_manager %}<i class="fas fa-user-check"></i>{% else %}<i class="fas fa-user-slash"></i>{% endif %}
                </label>
              </div>
              {% include 'include/errors.html' with errors=form.is_system_manager.errors %}
              {% if form.hidden_is_system_manager %}
              {{ form.hidden_is_system_manager.as_hidden }}
              {% include 'include/errors.html' with errors=form.hidden_is_system_manager.errors %}
              {% endif %}
            </div>
          </li>
          <li class="list-group-item">
            <div class="d-grid gap-2 my-2">
              <button id="submit_edit_manager" type="submit" class="btn btn-primary">変更</button>
            </div>
          </li>
        </ul>
      
      
      </form>
    </div>
  </div>
  <!-- end of search_form row -->
</div>
{% endblock content %}

{% block script %}
<script src="{% static 'js/edit_manager.js' %}" type="text/javascript"></script>
{% endblock %}

web/templates/management/menu/manager_list.html
{% extends 'management/menu/base.html' %}
{% load static %}

{% block title %}予約一覧{% endblock %}

{% block style %}
<link href="{% static 'css/datetimepicker.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="container">
  <!-- search_form row -->
  <div class="row mt-5 justify-content-center">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <form id="manager_list_search_form" method="get" action="">
            {{ form.only_not_authorized_flg }}{{ form.only_not_authorized_flg.label_tag }}
            {% include 'include/errors.html' with errors=form.only_not_authorized_flg.errors %}
          </form>
        </div>
      </div>
    </div>
  </div>
  <!-- end of search_form row -->
  
  <!-- page_obj row -->
  <div class="row">
    <div class="col-12">
      {% for manager in page_obj %}
      <div class="card mt-4">
        <div class="card-body">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">{{ manager.name }}</li>
            <li class="list-group-item">{{ manager.mail_address }}</li>
            <li class="list-group-item">
              管理者承認&emsp;
              {% if manager.is_authorized %}<i class="far fa-check-circle" style="color: green"></i>
              {% else %}<i class="fas fa-times-circle" style="color: red"></i>{% endif %}
            </li>
            <li class="list-group-item">
              システムマネージャー&emsp;
              {% if manager.is_system_manager %}<i class="far fa-check-circle" style="color: green"></i>
              {% else %}<i class="fas fa-times-circle" style="color: red"></i>{% endif %}
            </li>
          </ul>
          <div class="d-grid gap-2 mt-1">
            <a class="btn btn-success" href="{% url 'management:edit_manager' manager.id %}" role="button">編集</a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
  <!-- end of page_obj row -->
  
  <!-- paginator row-->
  <div class="row mt-4">
    <div class="col-12">
      {% include 'include/paginator.html' %}
    </div>
  </div>
  <!-- end of paginator row -->

</div>
{% endblock content %}

{% block script %}
<script src="{% static 'js/manager_list.js' %}" type="text/javascript"></script>
{% endblock %}