web/appointment/urls.py
from django.urls import path
from . import views

app_name = 'appointment'

urlpatterns = [
    path('', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('make_appointment/', views.make_appointment, name='make_appointment'),
    path('delete_appointment/', views.delete_appointment, name='delete_appointment'),
]

web/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('appointment/', include('appointment.urls', namespace='appointment')),
    path('management/', include('management.urls', namespace='management')),
]

web/appointment/models.py
from django.db import models
from django.core.validators import MinLengthValidator

from core.models import BaseModel


class Customer(BaseModel):
    """顧客"""
    name = models.CharField('名前', max_length=50)
    phone_number = models.CharField('電話番号', validators=[MinLengthValidator(10)], max_length=12)

    class Meta:
        db_table = "customer"
        verbose_name_plural = "顧客"
        unique_together = ["name", "phone_number"]

    def __str__(self):
        return self.name


class Car(BaseModel):
    """車"""
    name = models.CharField('名前', max_length=255)
    number = models.CharField('ナンバープレート4桁', validators=[MinLengthValidator(4)], max_length=4)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)

    class Meta:
        db_table = "car"
        verbose_name_plural = "車"

    def __str__(self):
        return "{}/{}（{}）".format(self.name, self.number, self.customer.name)


class Appointment(BaseModel):
    """来店予約"""
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    visit_at = models.DateTimeField("予約日時")
    visiting_purpose = models.CharField('来店理由', max_length=255)

    class Meta:
        db_table = "appointment"
        verbose_name_plural = "来店予約"

    def __str__(self):
        return "{}（{}）".format(self.customer.name, self.visit_at)

web/appointment/forms.py
import re

from datetime import datetime

from django import forms
from django.core.exceptions import MultipleObjectsReturned, ObjectDoesNotExist

from appointment.models import Appointment, Customer


class AppointmentForm(forms.Form):
    visit_date = forms.DateField(
        label="日付",
        input_formats=['%Y/%m/%d'],
        widget=forms.TextInput(
            attrs={
                'class': 'form-control datetimepicker-input date-picker',
                'data-target': '#date-picker',
                'placeholder': 'YYYY/mm/dd',
                'autocomplete': 'off',
            }
        )
    )
    visit_time = forms.TimeField(
        label="時刻",
        widget=forms.TextInput(
            attrs={
                'class': 'form-control datetimepicker-input time-picker',
                'data-target': '#time-picker',
                'placeholder': 'HH:MM',
                'autocomplete': 'off',
            }
        )
    )
    visiting_purpose = forms.CharField(
        label="ご来店理由",
        max_length=255,
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'rows': '3',
            }
        )
    )

    def __init__(self, customer_id: int, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.customer_id = customer_id

    def clean(self):
        now = datetime.now()
        if Appointment.objects.filter(customer_id=self.customer_id, visit_at__gte=now).exists():
            self.add_error(None, '既に予約されています。')

        cleaned_data = self.cleaned_data
        visit_date = cleaned_data['visit_date']
        visit_time = cleaned_data['visit_time']
        visit_at = datetime.combine(visit_date, visit_time)
        if visit_at < now:
            self.add_error('visit_time', '予約時刻が現在時刻より前です。')

        return cleaned_data


class LoginForm(forms.Form):
    name = forms.CharField(label="お名前", max_length=50)
    phone_number = forms.CharField(label="電話番号", help_text="数字のみ；ハイフン不可", min_length=10, max_length=12)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['phone_number'].widget.attrs['aria-describedby'] = 'phoneNumberHelp'
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control mt-1'

    def clean(self):
        cleaned_data = self.cleaned_data
        name = cleaned_data['name']
        phone_number = cleaned_data['phone_number']
        try:
            Customer.objects.get(name=name, phone_number=phone_number)
        except ObjectDoesNotExist:
            self.add_error('phone_number', 'お名前もしくは電話番号が間違っています。')
        except MultipleObjectsReturned:
            self.add_error('phone_number', 'ご入力いただいたユーザー情報が複数見つかりました。\nお手数ですが担当者にご連絡ください。')

        return cleaned_data

web/appointment/views.py
from datetime import datetime

from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned, ValidationError
from django.http import HttpResponse
from django.views.decorators.http import require_POST
from django.shortcuts import redirect, render

from appointment.forms import AppointmentForm, LoginForm
from appointment.models import Customer, Appointment
from core.decorators import customer_login_required, require_GET_POST


@require_GET_POST
def login(request):
    """ログイン"""
    if request.session.get('customer_id'):
        return redirect('appointment:make_appointment')
    form = LoginForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            name = form.cleaned_data['name']
            phone_number = form.cleaned_data['phone_number']
            customer = Customer.objects.get(name=name, phone_number=phone_number)
            request.session["customer_id"] = customer.id
            return redirect('appointment:make_appointment')

    return render(request, 'appointment/login.html', {'form': form})


@customer_login_required
@require_POST
def logout(request):
    """ログアウト"""
    if request.session.get('customer_id'):
        del request.session["customer_id"]
    return redirect('appointment:login')


@customer_login_required
@require_GET_POST
def make_appointment(request):
    """来店予約"""
    now = datetime.now()
    form = AppointmentForm(request.customer.id, request.POST or None)

    if request.method == "POST":
        if form.is_valid():
            visit_date = form.cleaned_data['visit_date']
            visit_time = form.cleaned_data['visit_time']
            visiting_purpose = form.cleaned_data['visiting_purpose']
            visit_at = datetime.combine(visit_date, visit_time)
            Appointment.objects.create(
                customer=request.customer,
                visit_at=visit_at,
                visiting_purpose=visiting_purpose,
            )
            messages.success(request, "ご来店を予約しました。")
            return redirect('appointment:make_appointment')

    appointment = None
    try:
        appointment = Appointment.objects.get(
            customer=request.customer,
            visit_at__gte=now,
        )
        for field in form.fields.values():
            field.widget.attrs['disabled'] = 'disabled'
    except MultipleObjectsReturned:
        Appointment.objects.filter(
            customer=request.customer,
            visit_at__gte=now,
        ).delete()
        return HttpResponse('複数のご予約が見つかりました。<br>画面をリロードし、再度ご予約ください。')
    except ObjectDoesNotExist:
        pass

    ret = {'form': form, 'appointment': appointment}

    return render(request, 'appointment/appointment.html', ret)


@customer_login_required
@require_POST
def delete_appointment(request):
    """来店予約削除"""
    now = datetime.now()
    customer = Customer.objects.get(id=request.customer.id)
    appointment_qs = Appointment.objects.filter(
        customer=customer,
        visit_at__gte=now,
    )
    if appointment_qs.exists():
        appointment_qs.delete()
        messages.success(request, "ご来店予約を削除しました。")
    else:
        messages.error(request, "ご来店は予約されていません。")
    return redirect('appointment:make_appointment')

web/templates/appointment/appointment.html
{% extends 'appointment/base.html' %}
{% load static %}

{% block title%}ログイン{% endblock%}

{% block style %}
<link href="{% static 'css/datetimepicker.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="container">
  {% include 'include/messages.html' %}
  <div class="row mt-5 justify-content-center">
    <div class="col-10">
      <div class="card">
        <div class="card-header">
          
          {% if appointment %}
          ご予約日時:<br>
          <span style="color: red;">{{ appointment.visit_at|date:"Y年m月d日 H時i分" }}</span><br>
          ご来店理由:<br>
          {{ appointment.visiting_purpose }}
          {% else %}ご予約日時: なし{% endif %}
        </div>
        <div class="card-body">
          <form method="post">
            {% csrf_token %}
            {% include 'include/non_field_errors.html' %}
            
            <div class="mb-3">
              <span>{{ form.visit_date.label_tag }}</span>
              <div class="input-group date mb-3" id="date-picker" data-target-input="nearest">
                {{ form.visit_date }}
                <div class="input-group-text  date-picker-icon" data-target="#date-picker" data-toggle="datetimepicker">
                  <i class="far fa-calendar-alt"></i>
                </div>
              </div>
              {% include 'include/errors.html' with errors=form.visit_date.errors %}
            </div>
            
            <div class="mb-3">
              <span>{{ form.visit_time.label_tag }}</span>
              <div class="input-group date mb-3" id="time-picker" data-target-input="nearest">
                {{ form.visit_time }}
                <div class="input-group-text time-picker-icon" data-target="#time-picker" data-toggle="datetimepicker">
                  <i class="far fa-clock"></i>
                </div>
              </div>
              {% include 'include/errors.html' with errors=form.visit_time.errors %}
            </div>
            
            <div class="mb-3">
              {% include 'include/field_errors.html' with field=form.visiting_purpose %}
            </div>
            
            <div class="d-grid gap-2">
              {% if appointment %}
              <button class="btn btn-info" type="button" data-bs-toggle="modal" data-bs-target="#exampleModal">予約を削除
              </button>
              {% else %}
              <button class="btn btn-primary" type="submit">送信</button>
              {% endif %}
            </div>
          
          </form>
        </div>
      </div>
    </div>
  </div>
</div>


{% include 'modal/delete_appointment_conf.html' %}
{% endblock %}

{% block script %}
<script src="{% static 'js/datetimepicker.js' %}" type="text/javascript"></script>
{% endblock %}

web/templates/appointment/base.html
{% extends 'base.html' %}
{% load static %}

{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="">ご来店予約</a>
    <div class="d-flex">
      {% if request.customer %}
      <span class="navbar-text me-3">{{ request.customer }} 様</span>
      <button class="btn btn-secondary btn-sm" type="button" data-bs-toggle="modal" data-bs-target="#logoutModal">ログアウト
      </button>
      {% else %}
      <span class="navbar-text">ログイン</span>
      {% endif %}
    </div>
  </div>
</nav>

<!-- ログアウトボタン押下時の確認用モーダル -->
<div class="modal" id="logoutModal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">ご確認</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>ログアウトしますか？</p>
      </div>
      <div class="modal-footer">
        <form id="deleteForm" method="post" action="{% url 'appointment:logout' %}">{% csrf_token %}</form>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">いいえ</button>
        <button form="deleteForm" class="btn btn-primary">ログアウト</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

web/templates/appointment/login.html
{% extends 'appointment/base.html' %}
{% load static %}

{% block title%}ログイン{% endblock%}

{% block content %}
<div class="container">
  {% include 'include/messages.html' %}
  <div class="row mt-5 justify-content-center">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <form method="post">
            {% csrf_token %}
            <div class="mb-3">
              {% include 'include/field_errors.html' with field=form.name %}
            </div>
            <div class="mb-3">
              {% include 'include/field_errors.html' with field=form.phone_number %}
              <div id="phoneNumberHelp" class="form-text">{{ form.phone_number.help_text }}</div>
            </div>
            <div class="d-grid gap-2">
              <button class="btn btn-primary" type="submit">送信</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock%}