web/appointment/urls.py
from django.urls import path
from . import views

app_name = 'appointment'

urlpatterns = [
    path('', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('make_appointment/', views.make_appointment, name='make_appointment'),
    path('delete_appointment/', views.delete_appointment, name='delete_appointment'),
]

web/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('appointment/', include('appointment.urls', namespace='appointment')),
    path('management/', include('management.urls', namespace='management')),
]

web/templates/modal/delete_appointment_conf.html
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">
          削除してもよろしいですか？
        
        </h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>
          ご予約日時:<br>
          <span style="color: red;">{{ appointment.visit_at|date:"Y年m月d日（D） H時i分" }}</span>
        </p>
        <p class="mb-0">
          ご予約理由:<br>
          {{ appointment.visiting_purpose }}
        </p>
      </div>
      <div class="modal-footer">
        <form id="delete-form" action="{% url 'appointment:delete_appointment' %}" method="post">
          {% csrf_token %}
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">キャンセル</button>
          <button type="submit" class="btn btn-primary">削除</button>
        </form>
      </div>
    </div>
  </div>
</div>